# Generated by Django 3.2 on 2023-02-02 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя поля содержит недопустимый символ', regex='^[\\w.@+-]+\\z')], verbose_name='Имя пользователя'),
        ),
    ]
